model_params:
  name: 'FactorVAE'
  in_channels: 3
  latent_dim: 128
  gamma: 6.4

data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  submodel: 'discriminator'
  retain_first_backpass: True
  LR: 0.005
  weight_decay: 0.0
  LR_2: 0.005
  scheduler_gamma_2: 0.95
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 10

logging_params:
  save_dir: "logs/"
  name: "FactorVAE"  
  

