model_params:
  name: 'GammaVAE'
  in_channels: 3
  latent_dim: 128
  gamma_shape: 8.
  prior_shape: 2.
  prior_rate: 1.


data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.003
  weight_decay: 0.00005
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 10
  gradient_clip_val: 0.8

logging_params:
  save_dir: "logs/"
  name: "GammaVAE"
